[workspace]
repository = "github.com/dioderobot/arduino"
pcb-version = "0.3"
members = [
    "components/*",
    "reference/*",
    "modules/*",
    "boards/*",
]
vendor = ["github.com/diodeinc/registry/**"]

[access]
allow = ["*@arduino.cc"]
